export const BASE_URL = "https://api.dsep-bap-client.becknprotocol.io"
export const ENDPOINT = {
  INIT_APLLICATION: "/job/init",
  SUBMIT_APLLICATION: "/job/confirm",
  SEARCH_JOBS: "/job/search",
  SELECT_JOBS:"/job/select",
  USER_PROFILE: "/user/profile",
  MENTORSHIP_SELECT: "/mentorship/select",
  GET_SCHOLARSHIPS:'/scholarship/search',
  SCHOLARSHIP_SELECT: "/scholarship/select", 
  SCHOLARSHIP_INIT:"/scholarship/init", 
  CONFIRM_SCHOLARSHIP:'/scholarship/confirm',
  GET_MENTOR: '/mentorship/search',
  SEARCH_MENTORSHIP: '/mentorship/search',
  SELECT_MENTORSHIP: '/mentorship/select',
  CONFIRM_MENTORSHIP: '/mentorship/confirm',
  SELECT_TRAINING: '/course/select',
  INIT_TRAINING:'/course/init',
  CONFIRM_TRAINING:'/course/confirm',
};
